### ISSUE TITLE
DorsalVR and Dolphin start, but controls don't work, and in controller config dolphin shows [disconnected] before the controller input name.

### ISSUE THREAD

**Issue by VisibleReality** [MichaelJW/DorsalVR#18]
![image](https://user-images.githubusercontent.com/37581230/147259039-5281760d-8a3e-41b2-ab99-c304ec362e41.png)

DorsalVR starts as normal, and starts up dolphin. I can see the virtual screen in the HMD and my controllers are tracked (showing up as white blocks). However, whenever I start a game, the controls do nothing. Both pointing and button presses do not work.

![image](https://user-images.githubusercontent.com/37581230/147259243-16067780-1657-4181-841a-f6b408166a82.png)

DorsalVR shows up in alternate input sources, but it doesn't work.

I'm using SteamVR with valve index controllers.

My config file is as follows:
`default.yaml`
```yaml
%YAML 1.1
---
imports:
- WiiExample.yaml
dolphin:
  exePath: E:\Dolphin-x64\Dolphin.exe
  configDir: C:\Users\ajdmi\Documents\Dolphin Emulator\Config
...
```
`WiiExample.yaml`
```yaml
%YAML 1.1
---
imports:
- examples/WidescreenTV.yaml
- examples/PointerIMUs.yaml
- examples/Wiimote.yaml
- examples/ValveIndex.yaml
...
```
[Player.log](https://github.com/MichaelJW/DorsalVR/files/7770107/Player.log)
