### ISSUE TITLE
Buttons not mapping correctly from VR controllers

### ISSUE THREAD

**Issue by dpraul** [MichaelJW/DorsalVR#4]
Hi there! Been trying this out and something isn't quite right - Dolphin starts and I get the floating window after I launch a game, but the buttons on my controllers aren't passing through. When I check the controller config in Dolphin, I see that the Wiimote is set to the emulated controller and seems to be mapped to DorsalVR, but when I try pressing any of the buttons none none light up (although sometimes the trigger does?). When I tried the GameCubeExample, I had to manually select the controller to be from DorsalVR, but still none of the buttons worked except occasionally the trigger.

DorsalVR version: 2.0.1
Headset: HTC Vive (original) through SteamVR
Controllers: Valve Index controllers and HTC Vive wands (tried both)
Dolphin version: 5.0-14382 and 5.0-14596 (tried both)

I used the following config for Metroid Prime Trilogy, and I tried the `GameCubeExample` import with Metroid Prime 1:
```yaml
%YAML 1.1
---
imports:
- examples/WiiExample.yaml
dolphin:
  exePath: C:\games\Dolphin-x64\Dolphin.exe
  configDir: C:\Users\Dylan\Documents\Dolphin Emulator\Config
...
```
